#!/usr/bin/env bash
### end common-components/bash-shebang

# Welcome to the codica laptop script! Be prepared to turn your laptop (or
# desktop, no haters here) into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift

  # shellcheck disable=SC2059
  printf "\n$fmt\n" "$@"
}

fancy_echo "Installing git, for source control management ..."
  sudo apt install -y git

fancy_echo "Installing libraries for common gem dependencies ..."
  sudo apt install -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libqtwebkit-dev libreadline-dev

fancy_echo "Installing sqlite3, for prototyping database-backed rails apps ..."
 sudo apt install -y libsqlite3-dev sqlite3

fancy_echo "Installing Postgres, a good open source relational database ..."
  sudo apt install -y postgresql postgresql-server-dev-all

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  sudo apt install -y tmux

fancy_echo "Installing guake, a super terminal"
  sudo apt install -y guake

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  sudo apt install -y imagemagick

fancy_echo "Installing curl ..."
  sudo apt install -y curl

fancy_echo "Installing zsh ..."
  sudo apt install -y zsh

fancy_echo "Installing node, to render the rails asset pipeline ..."
  sudo apt install -y nodejs

fancy_echo "Installing npm ..."
  sudo apt install -y npm

fancy_echo "Installing RVM"
command curl -sSL https://rvm.io/mpapis.asc | gpg2 --import -
\curl -sSL https://get.rvm.io | bash -s stable --ruby

fancy_echo "Configuring Bundler for faster, parallel gem installation ..."
  gem install bundler
  bundle config --global jobs 5

fancy_echo "Installing Heroku CLI client ..."
  curl -s https://toolbelt.heroku.com/install-ubuntu.sh | sh

fancy_echo "Installing the heroku-config plugin to pull config variables locally to be used as ENV variables ..."
  heroku plugins:install git://github.com/ddollar/heroku-config.git

fancy_echo "Installing chrome ..."
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  sudo apt update
  sudo apt install -y google-chrome-stable

fancy_echo "Installing oh-my-zsh ..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
