#!/usr/bin/env bash
### end common-components/bash-shebang

# Welcome to the codica laptop script! Be prepared to turn your laptop (or
# desktop, no haters here) into an awesome development machine.

fancy_echo() {
  local fmt="$1"; shift
  printf "\n$fmt\n" "$@"
  }

fancy_echo "Installing git, for source control management ..."
  sudo apt install -y git

fancy_echo "Installing libraries for common gem dependencies ..."
  sudo apt install -y libxslt1-dev libcurl4-openssl-dev libksba8 libksba-dev libqtwebkit-dev libreadline-dev build-essential apt-transport-https ca-certificates gnupg-agent software-properties-common

fancy_echo "Installing snapd canonical package manager"
  sudo apt install -y snapd

fancy_echo "Installing VLC media player"
  sudo snap install vlc

fancy_echo "Installing Postman API development environment"
  sudo snap install postman

fancy_echo "Installing simple screen recorder"
  sudo apt install -y simplescreenrecorder

fancy_echo "Installing Joxi"
  wget -q "http://dl.joxi.ru/linux/joxi-amd64.deb"
  sudo apt install -y ./joxi-amd64.deb
  rm joxi-amd64.deb

fancy_echo "Installing sqlite3, for prototyping database-backed rails apps ..."
 sudo apt install -y libsqlite3-dev sqlite3

fancy_echo "Installing Postgres, a good open source relational database ..."
  sudo apt install -y postgresql postgresql-server-dev-all

fancy_echo "Installing tmux, to save project state and switch between projects ..."
  sudo apt install -y tmux

fancy_echo "Installing guake, a super terminal"
  sudo apt install -y guake

fancy_echo "Installing ImageMagick, to crop and resize images ..."
  sudo apt install -y imagemagick libmagickwand-dev

fancy_echo "Installing curl ..."
  sudo apt install -y curl

fancy_echo "Installing Redis ..."
  wget http://download.redis.io/redis-stable.tar.gz &&
  tar xvzf redis-stable.tar.gz &&
  cd redis-stable  && make
  sudo cp src/redis-server /usr/local/bin/
  sudo cp src/redis-cli /usr/local/bin/

fancy_echo "Installing Ngrok ..."
  wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip && unzip ngrok-stable-linux-amd64.zip && rm ngrok-stable-linux-amd64.zip

fancy_echo "Installing Sublime Text 3 ..."
  wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
  echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
  sudo apt update && sudo apt install -y sublime-text

fancy_echo "Installing VS Code ..."
  curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
  sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main" > /etc/apt/sources.list.d/vscode.list'
  sudo apt update && sudo apt install -y code

fancy_echo "Installing Unity Tweak Tool ..."
  sudo apt install -y unity-tweak-tool

fancy_echo "Installing zsh ..."
  sudo apt install -y zsh

fancy_echo "Installing node, to render the rails asset pipeline ..."
  curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
  sudo apt install -y nodejs

fancy_echo "Installing RVM"
  gpg2 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E37D2BAF1CF37B13E2069D6956105BD0E739499BDB
  \curl -sSL https://get.rvm.io | bash -s -- --ignore-dotfiles
  echo "source $HOME/.rvm/scripts/rvm" >> ~/.bash_profile
  [[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm" 

fancy_echo "Installing Ruby"
  sudo apt install -y ruby

fancy_echo "Installing Heroku CLI client ..."
  curl -s https://toolbelt.heroku.com/install-ubuntu.sh | sh

fancy_echo "Installing the heroku-config plugin to pull config variables locally to be used as ENV variables ..."
  heroku plugins:install git://github.com/ddollar/heroku-config.git

fancy_echo "Installing chrome ..."
  wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
  sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  sudo apt update
  sudo apt install -y google-chrome-stable

fancy_echo "Generating ssh key"
  ssh-keygen -b 4096 -t ed25519 -f /home/user/.ssh/key-ed25519 -q -N "" -C "$1"
  sudo mv ~/.config/autostart/gnome-keyring-ssh.desktop ~/.config/autostart/gnome-keyring-ssh.backup 
  ssh-add /home/user/.ssh/key-ed25519

fancy_echo "Installing Docker"
  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"
  sudo apt-get update
  sudo apt-get install -y docker-ce docker-ce-cli containerd.io

fancy_echo "Installing Wine"
  wget -nc https://dl.winehq.org/wine-builds/winehq.key
  sudo apt-key add winehq.key
  sudo apt-add-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
  sudo apt update
  sudo apt install -y --install-recommends winehq-stable

  fancy_echo "Installing oh-my-zsh ..."
  sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
